### ISSUE TITLE
Upgrade to node v18

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate-approve-bot-bitbucket-cloud#166]
I think it's safe to migrate to node v16

**Comment by maxbrunet** [comment]
I guess it is not as simple as opening and merging the Renovate PR

* Do we need to update `engines` in `packages.json` to v16 or do we do [like Renovate's `package.json`](https://github.com/renovatebot/renovate/blob/32.6.10/package.json#L122-L129)?
https://github.com/renovatebot/renovate-approve-bot-bitbucket-cloud/blob/fde3f1a0799e4511d28cbebd4b35b152b859ba37/package.json#L36-L38
* Node v16 comes with `npm` v8 and a new lockfile format, do we need to update the lockfile format from v1 to v2? or even v3? https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion
* Will it require a major version bump?

**Comment by viceice** [comment]
Node v18 is LTS and v14 is already EOL
