### ISSUE TITLE
Run linters on incoming PRs and pushes to `main`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate-approve-bot-bitbucket-cloud#50]
You can run the `npm run lint` command locally to check for any linting errors.

We should have a GitHub Action workflow file that runs the linters on incoming PRs - and pushes to the `main` branch - to catch any bad stuff before it hits `main`.

**Comment by HonkingGoose** [comment]
Turns out we already do this. Ignore this issue. 😉

**Comment by maxbrunet** [comment]
Yes, I have tried to follow your practices closely :)
