### ISSUE TITLE
Create issue forms

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate-approve-bot-bitbucket-cloud#52]
The main Renovate repository has nice issue forms, so that people who report a bug or request a feature are sure to give all the information we need.

Right now we don't have any issue forms.
Opening a issue to discuss what information we need. 😉

**Comment by maxbrunet** [comment]
Similar to https://github.com/renovatebot/renovate-approve-bot-bitbucket-cloud/issues/53#issuecomment-978177958, this can be handle together
