### ISSUE TITLE
Create PR template

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate-approve-bot-bitbucket-cloud#53]
There is no template given when you open a PR on this repository.
I'd like to have a template. 😄 

This issue is to discuss what kind of information we want to display in the PR template.
Or maybe we just want to copy/paste and adjust the PR template from the main Renovate repository?

**Comment by maxbrunet** [comment]
Thank you for your enthusiasm, I do not think this repo will receive a lot of contributions, that said if you want to open a PR, I will review it

To have an idea of how much work will happen here, you can have a look at https://github.com/renovatebot/renovate-approve-bot
