### ISSUE TITLE
Fix Semantic Commit bot on this repository

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate-approve-bot-bitbucket-cloud#56]
The `Semantic Pull Request` check is not running on incoming pull requests.

https://github.com/renovatebot/renovate-approve-bot-bitbucket-cloud/blob/e9bdc7db960995bd6543dbe93d481bc6e45118fb/.github/semantic.yml#L1-L4

**Comment by maxbrunet** [comment]
@rarkins could you grant me back admin on the repo, please? I will check this kind of settings

**Comment by rarkins** [comment]
@maxbrunet now done

**Comment by maxbrunet** [comment]
Thank you @rarkins, I have reinstalled all the integrations (renovate, approve bots, semantic pull requests)
