### ISSUE TITLE
Use CodeQL to check code in this repository

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate-approve-bot-bitbucket-cloud#57]
The main Renovate bot repository uses GitHub CodeQL to check for possible security problems in the code.
It's probably a good idea to enable CodeQL [^gh-docs] on this repository as well.

[^gh-docs]: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning

**Comment by maxbrunet** [comment]
Security scanning is always good and it happens to be free, as I said in https://github.com/renovatebot/renovate-approve-bot-bitbucket-cloud/issues/58#issuecomment-978184575 I kept it simple and did not enable everything https://github.com/renovatebot/renovate has
